[tox]
envlist = py310, py311

[testenv]
deps = -rrequirements_dev.txt
commands =
    # Linting for syntax errors
    flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
    flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # Type checking
    mypy src/
    # Unit tests
    pytest -v tests/unit
    # Integration tests
    pytest -v tests/integration
